### ISSUE TITLE
endless loop in some case

### ISSUE THREAD

**Issue by kthh07** [Yorkyer/edmonds-blossom#5]
The program will be stuck in an endless loop in this case:

edges = [(1, 3), (1, 7), (1, 4), (7, 8), (7, 1), (7, 2), (7, 9), (5, 2), (8, 3), (8, 7), (8, 4), (8, 6), (4, 1), (4, 2), (4, 8), (4, 9), (3, 8), (3, 2), (3, 9), (3, 1), (3, 6), (2, 7), (2, 3), (2, 0), (2, 4), (2, 5), (0, 2), (6, 8), (6, 3), (9, 3), (9, 4), (9, 7)]
match = Match.from_edges(10, edges)

**Comment by Yorkyer** [comment]
Hi, I just fixed the bug. Sorry for the late reply here, and I've been a little busy recently:)

The bug is related to finding the augmenting path in a blossom. As in the figure below, [1, 3, 6, 8, 4] is the blossom, and [1, 3], [4, 8] is the existed match. When choosing the next node from 3's neighbor nodes with the partial augmenting path [7, 1, 3], the unmatched node in the blossom has priority and should be selected first.

![image](https://github.com/yorkyer/edmonds-blossom/assets/43461507/d30508cf-ec3c-46d2-9517-9ad02dec774e)
